### PR TITLE
Initial Commit

### PR DESCRIPTION
**Pull request by mjhult**
Initial project files without packages

### CODE REVIEW

**Review by Hidinkyu — APPROVED** [review]
alllll good

**Review by JamesJunJieHuang — APPROVED** [review]

**Comment by Ruizmichael** [comment]
nice

**Comment by zhiyi15** [comment]
nice

**Review by Hidinkyu — APPROVED** [review]

**Review by zhiyi15 — COMMENTED** [review]
checked!

**Review by Ruizmichael — APPROVED** [review]
we did it

**Review by zhiyi15 — APPROVED** [review]
nice

**Review by Ruizmichael — APPROVED** [review]
approved

**Pull request merged**
